name: Merge to Main Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify branch
        run: |
          if [[ ${{ github.event.pull_request.base.ref }} != 'main' ]]; then
            echo "Not merging into main branch. Exiting workflow..."
            exit 0
          fi

      - name: Set Docker image tag
        id: set_tag
        run: echo "::set-output name=tag::mydockerimage-$(date +%s)"

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ steps.set_tag.outputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: prateekp2f/mydockerimage:${{ steps.set_tag.outputs.tag }}
